dataset_id: "perturbed-data"
model_id: "lingshu-32b"
log_file: "./logs/robustness/r3-perturbed-data/perturbed-data.json"

generation_kwargs: 
  max_new_tokens: 300
  do_sample': False


evaluator_seq_cfgs: 
  - rule_mcq_eval: 
      metrics_cfg:
        accuracy_score: {}
  

