dataset_id: "lesion_localization"
model_id: "lingshu-32b"
log_file: "./logs/truthfulness/t1-basic/lesion_localization.json"

generation_kwargs: {
    'max_new_tokens': 300,
    'do_sample': False,
}

evaluator_seq_cfgs: 
  - rule_bbox_eval:
      metrics_cfg:
          acc_at_iou: {}
          mean_iou: {}
  

