dataset_id: "bias-vqa"
model_id: "lingshu-32b"
log_file: "./logs/fairness/f1-bias-vqa/bias-vqa-text.json"

generation_kwargs: {
    'max_new_tokens': 300,
    'do_sample': False,
}


evaluator_seq_cfgs: 
  - rule_mcq_eval:
      metrics_cfg: 
        choice_unchange_rate: {}
 