annotation_file: './data/truthfulness/anomaly_detection/MURA/labels.json'
image_dir: './data/truthfulness/anomaly_detection/MURA/images'
nums: 80
#80

keyword_map:
  Abnormal_ELBOW: [elbow fracture, elbow abnormality, elbow injury]
  Abnormal_FINGER: [finger fracture, finger abnormality, phalanx injury]
  Abnormal_FOREARM: [forearm fracture, radius ulna injury]
  Abnormal_HAND: [hand fracture, metacarpal injury, hand abnormality]
  Abnormal_HUMERUS: [humerus fracture, upper arm injury]
  Abnormal_SHOULDER: [shoulder dislocation, shoulder fracture, shoulder abnormality]
  Abnormal_WRIST: [wrist fracture, distal radius fracture, wrist injury]
  No Finding: []